spring:
  application:
    name: userApps
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${DATABASE}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp-relay.sendinblue.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  profiles:
    active: ${DEPLOY:prod}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_TOKEN}
      ssl:
        enabled: true
      timeout: 3000ms

server:
  port: 10102
  servlet:
    context-path: /v1/api

jwt:
  secret:
    key: ${JWT_KEY}
  expiration:
    access: 5
    refresh: 60

cors:
  origin:
    allowed: ${CORS_URL}

java:
  mail:
    from: ${EMAIL_FROM}

